apiVersion: v2
name: loki
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: promtail
    version: 6.16.4
    repository: https://grafana.github.io/helm-charts
