traefik:
  globalArguments:
    - "--global.checknewversion"

  providers:
    kubernetesIngress:
      publishedService:
        enabled: true

  ingressRoute:
    dashboard:
      entryPoints: ["websecure"]
      matchRule: Host(`traefik.homeserver.internal`)
      tls:
        secretName: traefik-cert

routes:
  argocd:
    hostname: argocd.homeserver.internal
    tls:
      secretName: argocd-cert
