argo-cd:
  params:
    server.insecure: true
  dex:
    enabled: false
  server:
    extraArgs:
      - --insecure
    config:
      kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"
      repositories: |
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
  repoServer:
    # Use init containers to configure custom tooling
    # https://argoproj.github.io/argo-cd/operator-manual/custom_tools/
    env:
      - name: SOPS_AGE_KEY_FILE
        value: /.config/sops/age/keys.txt
    volumes:
      - name: custom-tools
        emptyDir: {}
      - name: sops-age
        secret:
          secretName: sops-age

    initContainers:
      - name: install-ksops
        image: viaductoss/ksops:v4.2.1
        command: ["/bin/sh", "-c"]
        args:
          - echo "Installing KSOPS...";
            mv ksops /custom-tools/;
            mv kustomize /custom-tools/;
            echo "Done.";
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools
    volumeMounts:
      - mountPath: /usr/local/bin/kustomize
        name: custom-tools
        subPath: kustomize
      - mountPath: /usr/local/bin/ksops
        name: custom-tools
        subPath: ksops
      - mountPath: /.config/sops/age/keys.txt
        name: sops-age
        subPath: keys.txt

