apiVersion: v1
kind: Secret
metadata:
    namespace: postgresql
    name: postgresql-creds
type: Opaque
data:
    admin: ENC[AES256_GCM,data:+/BehLOSVm1pqZPhzS1FqA==,iv:NexoiXvw453bfxSAnZ18ivQsr4uCP0ZYAuUVRDCAHhc=,tag:oGmugWoXgZkSzhc8hhmyhg==,type:str]
    user: ENC[AES256_GCM,data:81rR9NlLV6snSO53Wvx0Sw==,iv:jMKPAiB5mgD1khah9QpjzU8SSnm7ImIK7kawoAIsKCE=,tag:xA9ANDUDcOU5dW++xkxIKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxph0jdshf3h6e9fl6ttq62d854w0y9dx69vq5rw3c7n5m4tp9cqarxh9s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbVN5eU5TTHRqUGswd2tI
            TGVseEhBZDNodUtRbWpQamVidXFqRGErSEhFCjVmNVhUWXhKaXAxeTh3RjBtdCtO
            V1dzMEZIbHgxTVVnUGxMN3Fsa1RIREUKLS0tIDZadURydHdtK2xmL2xhV0diR1dH
            eDBRMkVNdnYwc3JXcm9VdWY5cjlvRTQKBxQgYbx9uznqGqiZeHh7UIeQ++w6ncZW
            EkAiyTSWp4p1D6Ell1YAmq6ox102v39GM/Z4UYp4mzUWx0oNlRrfgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-02T15:21:14Z"
    mac: ENC[AES256_GCM,data:7gMh82JY5xPlvwtLoqJg7O/bOO6UWVEgJ2TY7TGGcCvrObks1cSW+Mznpfdov+x7EB/udxDDQIXqV/xU/YLiBbQfs7cQrLgmlaaRwP5odL4K85Wnf6nmq39/pdwzlp3zJUCOx4QbfOAlHZ4hHWzagYOeHZxau46+tXBjNRe5NJU=,iv:7MpKwPN20jHswr+FpcBR9ybSkM3h6dFBD+b7LWM8Yi0=,tag:wZecnTxos3AbP1cKUi8WrQ==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.7.1
