apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ksops-secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - ./ca-key-pair.enc.yaml
  - ./postgresql-creds.enc.yaml
